version: '3.9'

services:
  database:
    image: mysql:latest
    container_name: mysql-container
    command: --default-authentication-plugin=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dbname
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    container_name: php-container
    build:
      context: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php